name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Для ручного запуска

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Обновлено до v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3 # Обновлено до v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      working-directory: TechProgramming/TZ2

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: TechProgramming/TZ2

    - name: Run tests
      run: ./gradlew test
      working-directory: TechProgramming/TZ2

    # - name: Notify success
    #   if: success()
    #   run: curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$CHAT_ID -d text="All tests passed successfully."
    #   env:
    #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    #     CHAT_ID: ${{ secrets.CHAT_ID }}

    # - name: Notify failure
    #   if: failure()
    #   run: curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$CHAT_ID -d text="Some tests failed. Please check the logs."
    #   env:
    #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    #     CHAT_ID: ${{ secrets.CHAT_ID }}
