name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Для ручного запуска

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Обновлено до v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3 # Обновлено до v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      working-directory: TechProgramming/TZ2

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: TechProgramming/TZ2

    - name: Run tests and capture output
      id: run-tests
      run: ./gradlew test 2>&1 | tee test-results.txt
      working-directory: TechProgramming/TZ2

    - name: Notify success
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage -d chat_id=${{ env.CHAT_ID }} -d text="✅ Все ок. Все тесты прошли успешно."

    - name: Notify failure
      if: failure()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        TEST_RESULTS=$(cat TechProgramming/TZ2/test-results.txt)
        curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage -d chat_id=${{ env.CHAT_ID }} -d text="❌ Некоторые тесты не пройдены. Пожалуйста, проверьте логи. \n\n${TEST_RESULTS}"
